# Generated by Django 5.2 on 2025-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_rename_description_faq_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='titre',
        ),
    ]
