# Generated by Django 5.2 on 2025-04-09 11:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_remove_faq_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Politique de confidentialité', max_length=255)),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu')),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politique de confidentialité',
                'verbose_name_plural': 'Politiques de confidentialité',
            },
        ),
    ]
