# Generated by Django 5.2 on 2025-04-09 20:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('soustitre', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu')),
                ('image', models.ImageField(upload_to='about/principale/')),
                ('photo', models.ImageField(upload_to='about/secondaire/')),
                ('nom', models.CharField(max_length=255)),
                ('histore', django_ckeditor_5.fields.CKEditor5Field(verbose_name='histoire')),
                ('portrait', models.ImageField(upload_to='about/tertiaire/')),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'A propos de nous',
                'verbose_name_plural': 'A propos de nous',
            },
        ),
    ]
