# Generated by Django 5.2 on 2025-04-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_propos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propos',
            name='portrait',
            field=models.ImageField(upload_to='about/propos/'),
        ),
    ]
